language: java
before_install:
- openssl aes-256-cbc -K $encrypted_a3ce8dd0eaa7_key -iv $encrypted_a3ce8dd0eaa7_iv
  -in appdev-demo-7e87befc1137.json.enc -out appdev-demo-7e87befc1137.json -d
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
  -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install -y kubectl google-cloud-sdk google-cloud-sdk-app-engine-java
before_script:
- gcloud auth activate-service-account "travis-ci@appdev-demo.iam.gserviceaccount.com"
  --key-file=appdev-demo-7e87befc1137.json
- gcloud config set project appdev-demo
